-- US States + DC
INSERT IGNORE INTO states (code, name, country) VALUES
  ('AL', 'Alabama',              'USA'),
  ('AK', 'Alaska',               'USA'),
  ('AZ', 'Arizona',              'USA'),
  ('AR', 'Arkansas',             'USA'),
  ('CA', 'California',           'USA'),
  ('CO', 'Colorado',             'USA'),
  ('CT', 'Connecticut',          'USA'),
  ('DE', 'Delaware',             'USA'),
  ('FL', 'Florida',              'USA'),
  ('GA', 'Georgia',              'USA'),
  ('HI', 'Hawaii',               'USA'),
  ('ID', 'Idaho',                'USA'),
  ('IL', 'Illinois',             'USA'),
  ('IN', 'Indiana',              'USA'),
  ('IA', 'Iowa',                 'USA'),
  ('KS', 'Kansas',               'USA'),
  ('KY', 'Kentucky',             'USA'),
  ('LA', 'Louisiana',            'USA'),
  ('ME', 'Maine',                'USA'),
  ('MD', 'Maryland',             'USA'),
  ('MA', 'Massachusetts',        'USA'),
  ('MI', 'Michigan',             'USA'),
  ('MN', 'Minnesota',            'USA'),
  ('MS', 'Mississippi',          'USA'),
  ('MO', 'Missouri',             'USA'),
  ('MT', 'Montana',              'USA'),
  ('NE', 'Nebraska',             'USA'),
  ('NV', 'Nevada',               'USA'),
  ('NH', 'New Hampshire',        'USA'),
  ('NJ', 'New Jersey',           'USA'),
  ('NM', 'New Mexico',           'USA'),
  ('NY', 'New York',             'USA'),
  ('NC', 'North Carolina',       'USA'),
  ('ND', 'North Dakota',         'USA'),
  ('OH', 'Ohio',                 'USA'),
  ('OK', 'Oklahoma',             'USA'),
  ('OR', 'Oregon',               'USA'),
  ('PA', 'Pennsylvania',         'USA'),
  ('RI', 'Rhode Island',         'USA'),
  ('SC', 'South Carolina',       'USA'),
  ('SD', 'South Dakota',         'USA'),
  ('TN', 'Tennessee',            'USA'),
  ('TX', 'Texas',                'USA'),
  ('UT', 'Utah',                 'USA'),
  ('VT', 'Vermont',              'USA'),
  ('VA', 'Virginia',             'USA'),
  ('WA', 'Washington',           'USA'),
  ('WV', 'West Virginia',        'USA'),
  ('WI', 'Wisconsin',            'USA'),
  ('WY', 'Wyoming',              'USA'),
  ('DC', 'District of Columbia', 'USA');

-- Canadian provinces and territories
INSERT IGNORE INTO states (code, name, country) VALUES
  ('AB', 'Alberta',                      'Canada'),
  ('BC', 'British Columbia',             'Canada'),
  ('MB', 'Manitoba',                     'Canada'),
  ('NB', 'New Brunswick',                'Canada'),
  ('NL', 'Newfoundland and Labrador',    'Canada'),
  ('NS', 'Nova Scotia',                  'Canada'),
  ('ON', 'Ontario',                      'Canada'),
  ('PE', 'Prince Edward Island',         'Canada'),
  ('QC', 'Quebec',                       'Canada'),
  ('SK', 'Saskatchewan',                 'Canada'),
  ('NT', 'Northwest Territories',        'Canada'),
  ('NU', 'Nunavut',                      'Canada'),
  ('YT', 'Yukon',                        'Canada');

-- Memberships
INSERT IGNORE INTO memberships (name, annual_fee, savings_method, discount_percent, discount_desc) VALUES
  ('Thousand Trails', 1150.00, 'free_vs_avg',  NULL,  'Unlimited free nights'),
  ('KOA Rewards',       39.00, 'percent_off',  10.00, '10% off stays'),
  ('Good Sam',          30.00, 'percent_off',  10.00, '10% off stays');
